[package]
name = "practicas"
version = "0.1.0"
edition = "2024"

[dependencies]
is_prime = "2.0.9"
random-number = "0.1.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.96"
date_time = "2.2.0"
chrono = "0.4.40"
